# Generated by Django 6.0.4 on 2026-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=255, unique=True)),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(null=True, upload_to='imgd')),
            ],
        ),
    ]
